### ISSUE TITLE
Error when voice sample has nothing in it.

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-stt-plugin-chromium#5]
```
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]: 2024-01-13 15:13:13.444 - voice - ovos_dinkum_listener.plugins:finalize:35 - ERROR - Error in STT plugin: ChromiumSTT
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]: Traceback (most recent call last):
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_dinkum_listener/plugins.py", line 30, in finalize
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:     transcript = self.engine.execute(audio, self.language)
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_stt_plugin_chromium/__init__.py", line 248, in execute
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:     data = json.loads(result)["result"]
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:            ^^^^^^^^^^^^^^^^^^
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:   File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:     return _default_decoder.decode(s)
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:   File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:   File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Jan 13 15:13:13 rpi4b ovos-dinkum-listener[835]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JarbasAl** [comment]
now it just returns empty text, doesnt throw the json error
