### ISSUE TITLE
[BUG] sst plugin broken

### ISSUE THREAD

**Issue by geetee24** [OpenVoiceOS/ovos-stt-plugin-chromium#6]
2024-03-10 15:48:06.411 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:231 - INFO - Wakeword detected
2024-03-10 15:48:09.680 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:266 - INFO - speech finished
2024-03-10 15:48:09.988 - voice - ovos_dinkum_listener.plugins:finalize:35 - ERROR - Error in STT plugin: ChromiumSTT
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/plugins.py", line 30, in finalize
    transcript = self.engine.execute(audio, self.language)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_stt_plugin_chromium/__init__.py", line 245, in execute
    data = json.loads(result)["result"]
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-03-10 15:48:09.995 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:680 - INFO - nothing transcribed
2024-03-10 19:33:02.585 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:231 - INFO - Wakeword detected
2024-03-10 19:33:05.558 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:266 - INFO - speech finished
2024-03-10 19:33:06.131 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:678 - INFO - transcribed: TV Channel music

this is latest version of plugin

**Comment by JarbasAl** [comment]
that happens whenever google cant understand what you said, for example in a false activation or if it only recorded silence

in your logs you can see it working the second time 

> 2024-03-10 19:33:06.131 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:678 - INFO - transcribed: TV Channel music

guess we can make the error message less scary, but this is not a plugin bug, its the google ap returning empty results

NOTE: as it says in the readme, this api has been deprecated for a long time and is not supported officially by google, it might break at any time

**Comment by geetee24** [comment]
thank you BUT, when it works the second time as you said, OVOS does not get
it and my skill does not trigger.  So it is broken :(

**Comment by geetee24** [comment]
see more proof of broken plugin.

2024-03-10 19:59:31.282 - voice - ovos_stt_plugin_chromium:execute:246 - ERROR - aaa1: {"result":[]}
{"result":[{"alternative":[{"transcript":"TV channel CNN","confidence":0.94987679},{"transcript":"TV channels CNN","confidence":0.67861396},{"transcript":"teevee Channel CNN","confidence":0.94987679},{"transcript":"Tivi Channel CNN","confidence":0.94987679},{"transcript":"teavee Channel CNN","confidence":0.94987679}],"final":true}],"result_index":0}

2024-03-10 19:59:31.290 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:678 - INFO - transcribed: TV channel CNN

The skill DOES NOT Get the string "TV Channel CNN" since the plugin threw an  error.

**Comment by JarbasAl** [comment]
if your skill doesnt trigger with "TV Channel music" then it would be a bug in your intents most likely, not a bug with the STT plugin itself as the plugin job is ONLY to return the text

if you have error logs from core or your skill i can take a look, but will likely need a github link

**Comment by geetee24** [comment]
my skill worked perfect with Mycroft.   it fails with OVOS.   If I say
ovos-say-to "tv channel CNN" it DOES trigger.

If I speak into OVOs, it fails to trigger despite the logs showing google
translated it correctly

**Comment by JarbasAl** [comment]
if the error is the one on the original issue, then its a duplicate of https://github.com/OpenVoiceOS/ovos-stt-plugin-chromium/issues/5

the second log you shared its  from your modified code as that line does not correspond to any log in the plugin code, so its not a good proof of any error, its the results google returns as it says right in the code where tou added that log

https://github.com/OpenVoiceOS/ovos-stt-plugin-chromium/blob/dev/ovos_stt_plugin_chromium/__init__.py#L241
